
import Navbar from "@/Components/Navbar";
import "./globals.css";
import {Poppins, Roboto} from "next/font/google"
import Footer from "@/Components/Footer";



const poppins =  Poppins({
  subsets: ["latin"],
  weight: "400",
  variable : "--font-poppins"
})

const robotoFont = Roboto({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-roboto"
})


export const metadata = {
  title: "QuickCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body
        className={`${poppins.variable} ${robotoFont.variable} antialiased`}
      >

        <Navbar></Navbar>
        {children}

<Footer></Footer>
      </body>

    

    </html>
  );
}
